!!dev.wuffs.squatgrow.config.SquatGrowConfig
ae2Multiplier: 30
allowAdventureTwerking: true
chance: 100.0
debug: false
enableAE2Accelerator: true
enableDirtToGrass: true
enableMysticalCrops: true
hoeTakesDamage: false
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium']
randomTickMultiplier: 3000
range: 8
requireHoe: false
requirements:
  durabilityDamage: 1
  enabled: true
  equipmentRequirement: {}
  heldItemRequirement: []
  requiredEnchantment: ''
  requiredItemTakesDamage: false
sugarcaneMultiplier: 1000
useWhitelist: false
